### ISSUE TITLE
High Sierra (10.13) install blocking all but localhost

### ISSUE THREAD

**Issue by bonified2x** [glftpd/glftpd#10]
I've used glftpd before and I'm very familiar with it (on mac os x). I believe there's some issue with the latest version of mac os high sierra 10.13.3 and host name resolution.

I've also written on it here: https://becomethesolution.com/blogs/mac/install-glftpd-free-ftp-server-software-for-mac-x and will be updating the article once I get it figured out here.

I successfully installed / configured a gl site on my machine using the install.sh from mac os binaries (glftpd v2.08). I can access the site using "localhost" as the hostname. However, I can't access it with 127.0.0.1 as the host or from my machine internal IP address. I get "connection refused" and there are no login attempts logged in the gl log file. I don't have the mac os x firewall enabled.

I created my gl site with a high port (which works) and I can confirm the glftpd service is added in my /etc/services/ file.

I don't think its needed, but i added a hosts.allow in /jail/glftpd/etc/ and added "glftpd: ALL" to it.

Finally, I checked my machine host file and there is nothing in for custom configurations, outside local host entries.

So because I can't connect to my gl site with anything other than "localhost", I can't connect from outside either (yes I've forwarded ports on router and added the pasv ports and wan ip to gl conf).

I created a few users successfully and without identd (*@* users). 

Can someone confirm I've done everything correctly at this point. I'm also have this same issue on a mac running 10.12...

The lat time I configured gl successfully was back in 10.10 mac os.

**Comment by Skeddie** [comment]
Your "localhost" probably resolves to ::1 first. Check "/Library/LaunchDaemons/eu.glftpd.glftpd.plist" and change the `IPv6` in it to `IPv4`. Or remove the `<key>SockFamily</key><string>IPv6</string>` completely. Then reload launchd and test again.

**Comment by bonified2x** [comment]
And....that worked!! Should have double checked the plist it made. Thank you! Going to update my documentation :)

**Comment by Skeddie** [comment]
From your blogpost I see changing the value to IPv4 fixed it, but as this disables IPv6 functionality, could you test the second method as well (removing the option altogether)? Would be of great help for fixing the installer script.

**Comment by bonified2x** [comment]
Hi,
Yes. I just confirmed removing the following area from the plist file works to. I reloaded the plist after making the change and I can connect to my FTP site internally and externally (from a different WAN provider as well)

Removed this: `<key>SockFamily</key><string>IPv4</string>`

**Comment by Skeddie** [comment]
Splendid, thanks for the report and help.
