### ISSUE TITLE
glftpd runs into NULL ptr dereference on missing arguments for stat_section

### ISSUE THREAD

**Issue by eirau0Sh** [glftpd/glftpd#11]
If stat_section is missing yes/no at the end, glftpd runs into a segfault due to a strcmp being performed on the missing argument. This happens in several cases. The straight-forward one that I saw was issuing site user <user>.

HTH

**Comment by Skeddie** [comment]
As the glftpd.docs explain, all arguments for `stat_section` are mandatory. Leaving out the last argument is thus technically a configuration error.
The segfault you observed came from the %IX cookie and has been fixed.
As the `stat_section`handling code was a bit inconsistent, we have made the last argument optional, defaulting to "no".
Thanks for your report, fixes will come in an upcoming release.
