### ISSUE TITLE
glftpd login slowed down due to alarm(5) call

### ISSUE THREAD

**Issue by eirau0Sh** [glftpd/glftpd#12]
I have experienced a delay between connecting to a glftpd site and the login prompt of a few seconds.
Further inspection on why this happened lead me to an alarm(5) call within glftpd after the configuration file is read. This is how this looks like in strace:

ART, sa_restorer=0x7f2af2bf7030}, {sa_handler=0x43eb40, sa_mask=[ALRM], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f2af2bf7030}, 8) = 0
[pid  4067] alarm(5)                    = 0
[pid  4067] bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("XXXXX")}, 16) = 0
[pid  4067] connect(3, {sa_family=AF_INET, sin_port=htons(113), sin_addr=inet_addr("XXXXXX")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid  4067] --- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
[pid  4067] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid  4067] alarm(900)                  = 0
[pid  4067] close(3)                    = 0

As you can see, the connect call results in ERESTARTSYS because of this.

I patched the glftpd binary to issue only an alarm(1) instead of alarm(5) here so that I only have a login delay of one second.
However, I'm assuming there is a reason for the code to work like this that I currently don't understand. However, I see no side effects from my patched binary so far.

Can you tell me what the idea behind this mechanism is?

**Comment by Skeddie** [comment]
What you are observing is glftpd trying to determine the ident of the connecting host. A timeout of 5 seconds is set before giving up in trying to connect to the ident-server on the connecting host. If you want to disable this, use the -I flag in the corresponding inetd/xinetd/systemd/... config file, see glftpd.docs.

**Comment by Skeddie** [comment]
An upcoming release will allow you to specify the timeout via the -I inetd/xinetd/systemd/... config argument, alike the -n argument.
