### ISSUE TITLE
glftpd 2.08 freebsd x64 hangs at PASV out of the box

### ISSUE THREAD

**Issue by robnewmark** [glftpd/glftpd#13]
With a clean install of FreeBSD 11,1 x64 and a new install of glftpd 2.08 freebsd x64 with no configuration changes, dirlist hangs on PASV.

Using 2.07 freebsd x64 with the same default configuration, it works fine out of the box.

**Comment by Skeddie** [comment]
Confirmed and investigating.

**Comment by Skeddie** [comment]
Fixed in an upcoming release.
