### ISSUE TITLE
Change of credits from KB to MB

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#14]
I wonder if it's not time to upgrade the credit system from KB to MB consider that things today are far bigger than they been in the past. Thought I leave that as an idea for future changes especially since things are getting bigger and bigger which makes this change necessary sooner rather than later.

**Comment by Skeddie** [comment]
In userfile terms it's not necessary. And display-wise they're already shown in MiB. Whether display of sizes and speeds could use an upgrade from MiB to GiB and KB/s to MB/s is another question.
