### ISSUE TITLE
Cross compile glftpd for newer POWER processors

### ISSUE THREAD

**Issue by LEm00n** [glftpd/glftpd#17]
Hi,

It would be cool if glftpd worked natively on newer POWER processors. The gcc platform is ppc64le & ppc64. I think targeting ppc64le is reasonable first.

Raptor Computing Systems makes open source motherboards for POWER9:
https://www.raptorcs.com/

OpenPower Foundation:
https://openpowerfoundation.org/

IBM recently announced the Power ISA is going open source as well.

Thanks!

**Comment by glftpd** [comment]
Should be possible. I can see some toolchains even being part of ubuntu.

**Comment by glftpd** [comment]
done
