### ISSUE TITLE
site update <folder>, returns output for skipped lines

### ISSUE THREAD

**Issue by hrxcodes** [glftpd/glftpd#18]
I was not expecting "test2" to be printed to the console when targeting a specific folder with `site update test1`

Can this skipped response be disabled in config or removed?

Thanks

```
$ # ftp 127.0.0.1 1337
Connected to 127.0.0.1.
220 MY SITE NAME (glFTPd 2.09 (Dec 23 2018) 64BiT Linux+TLS(OpenSSL 1.1.0j  20 Nov 2018)+SSP) ready.
Name (127.0.0.1:root): glftpd
331 Password required for glftpd.
Password:
230-                                _____
230- ______________________________|__   |____ ________________________________
230- \     _      /   _     /  _     /   |    |    _     /  _     /    _      /
230-  \    \     /    /    /   /____/.   |    |    /    /   /____/.    /_____/
230-   \________/____/    /______    |___|____|___/    /______    |____|
230- .-=----------- /____/ ---- |____| --------- /____/ ---- |____| -------=-. 
230- `-=-------------------------------------------------------------------=-'
230-       `-----( Type 'site onel MESSAGE' to enter your message )-----'
230 User glftpd logged in.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> mkd test1
257 "/test1" created.
ftp> mkd test2
257 "/test2" created.
ftp> site update test1
200- Updating: /site/test1
200- Skipping test2
200 Command Successful.
```

**Comment by Skeddie** [comment]
Added a ```-s``` "silent" flag to the ```site update``` command which suppresses output of those "Skipping" lines. This way it is backward compatible with any script relying on this output.
If general opinion is that it should be the other way around, this can be changed to ```-v``` "verbose" to explicitly show those lines. Scripts need be updated then.
Also fixed appearance of the dirname in the "Updating" line.
Present in upcoming 2.10 beta.

**Comment by Skeddie** [comment]
A few other people preferred the ```-v``` solution so switching to that.
