### ISSUE TITLE
stats not excluding group

### ISSUE THREAD

**Issue by MrCodeFr** [glftpd/glftpd#2]
/glftpd/bin/stats -r /glftpd/etc/glftpd.conf -t -g EXCLUDEDGROUP
the stats returns all users in EXCLUDEDGROUP group.

note: the -e works well

**Comment by Skeddie** [comment]
The -g option is (was) only intended for the grouptops. The statsbin has however had a checkup where the -g option now also works for the usertops. In addition there's a new option -o <group> to only show user and grouptops from given groups, and the -e <user> now also works for the grouptops. A public releasedate of this updated statsbin is however unknown.

**Comment by Skeddie** [comment]
For reference, this stats-bin is available since 2.07 BETA 1.
