### ISSUE TITLE
Expand output length of nukes and new site commands

### ISSUE THREAD

**Issue by hrxcodes** [glftpd/glftpd#20]
The output of both `site nukes <num>` and `site new <num>` is often cut in width so not the full dirname is shown.
Could this be expanded?

Thanks

**Comment by Skeddie** [comment]
The output of those commands is generated through the ```glftpd/ftp-data/text/nukes.body``` and ```glftpd/ftp-data/text/new.body``` files. Raise or remove the number listed at the ```%[%s]Kd``` and ```%[%s]Nd``` cookies respectively.
