### ISSUE TITLE
Documentation for upgrade to new version of glFTPD 2.10

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#22]
In Slackware 14.2 when upgrading to glFTPD 2.10 BETA1 I get this message when trying to login

```
glftpd: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by glftpd)
glftpd: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by glftpd)
```

Maybe should be in upgrade notes that newer version of GLIBC is required to prevent people from doing an upgrade that may not work.

**Comment by glftpd** [comment]
glftpd for linux x86/x64 is always built on latest debian stable. It currently requires GLIBC_2.28 or higher.
For any other linux distribution please replace your glftpd binary with glftpd-full-static or upgrade :)
