### ISSUE TITLE
2.10beta1 CDUP not working on first level of directories

### ISSUE THREAD

**Issue by markrussinovichgithub** [glftpd/glftpd#23]
"CDUP" seems to work on deeper level of directories, but not on the first level of directories from the root. Example:

PWD
257 "/" is current directory.
CWD apps
250 CWD command successful.
PWD
257 "/apps" is current directory.
CWD isos
PWD
257 "/apps/isos" is current directory.
CDUP
250 CWD command successful.
PWD
**257 "/apps" is current directory.
CDUP
250 CWD command successful.
PWD
257 "/apps" is current directory.**

**Comment by glftpd** [comment]
fixed in B2
