### ISSUE TITLE
use_dir_size problem for clients

### ISSUE THREAD

**Issue by MrCodeFr** [glftpd/glftpd#24]
Some sysop activate the use_dir_size option.
It can be a nightmare to list huge folders on servers with poor capabilities.

Can you add the possibility (by password like the kill ghost) or in user profile to disable the dir_size?

Thanks

**Comment by Skeddie** [comment]
Your suggestion is taken into consideration and has a high percentage of inclusion. For reference I must correct that killghost is triggered by prefixing the username with a !, not the password.

**Comment by Skeddie** [comment]
Included in Beta3 by means of prefixing the username with '/'.
