### ISSUE TITLE
Credits still shown in MiB

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#25]
I see that credits are still shown in MiB during `site user username` in BETA2 even after implementing `display_size_unit g` in glftpd.conf. Is it possible to have it also shown in GiB/TiB?

**Comment by Skeddie** [comment]
Do you use ```%Ic``` or ```%IX``` in ```ftp-data/text/user.txt```? As you requested at #19 and as can be seen in the ```changelog```, only ```%Ic``` was changed.

**Comment by teqnodude** [comment]
This is the credits part in user.txt in BETA2 package
`!e| !gCredits!G: !C%[%-60s]IX !e|!0`

**Comment by Skeddie** [comment]
Alas the answer. So do "you" want ```%IX``` also to follow the ```display_size_unit``` option?

**Comment by teqnodude** [comment]
Yes that would be good.

**Comment by Skeddie** [comment]
Will be present in beta3.
