### ISSUE TITLE
Problem with site who in BETA2

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#26]
I get this error message when doing the command site who in BETA2

`550 ASSERT: (srclen + 1 <= dest_size) in file pids.c line 781 inside function gl_strcpy_internal`

**Comment by teqnodude** [comment]
Now I don't get it anymore all of a sudden, have no idea what caused it.

**Comment by glftpd** [comment]
caused by file names longer then 12 chars. will be fixed in next beta
