### ISSUE TITLE
Credits and Speed

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#29]
`site user` 
This is the last place I think that still show credits in MiB and that should follow the setting `display_size_unit`

`site who`
This is the last place I think that still show speed in K and that should follow the setting `display_speed_unit`

**Comment by Skeddie** [comment]
You probably mean ```site users```. Fixed in next beta. I however don't see anything wrong at ```site who``` output?

**Comment by teqnodude** [comment]
`site who` apparently shows K when nobody is downloading or uploading but shows MiB during traffic if `display_speed_unit` is set to `m`.

**Comment by Skeddie** [comment]
Not here so might be fixed after the version you're using. Maybe in beta4.
