### ISSUE TITLE
[R] 550 Error loading userfile for

### ISSUE THREAD

**Issue by thetrueisthere** [glftpd/glftpd#3]
i have sometime realy starnge problem with my glftpd.
Use pzs-ng with glftpd v2.06.2.
if don't delete data from glftpdpath/ftp-data/pzs-ng/site/*
then have error 550 Error loading userfile for ...
but i have a space: 15gb free
where is the problem?
Wed Mar 16 06:31:59 2016 [7998    ] Unable to create userfile /ftp-data/users/xx1.7998
Wed Mar 16 06:32:00 2016 [23961   ] Unable to create userfile /ftp-data/users/xx2.23961
Wed Mar 16 06:32:00 2016 [23951   ] Unable to create userfile /ftp-data/users/xx3.23951
Wed Mar 16 06:32:00 2016 [7998    ] Unable to create userfile /ftp-data/users/xx1.7998
Wed Mar 16 06:32:02 2016 [23961   ] Unable to create userfile /ftp-data/users/xx2.23961
Wed Mar 16 06:32:02 2016 [7998    ] Unable to create userfile /ftp-data/users/xx1.7998

**Comment by Stargrove** [comment]
Hi,
check out file rights. I saw a similar effect coming from an external script, I think it was the tur-autonuke script. 

Cheers

**Comment by Skeddie** [comment]
Might be you ran out of inodes, in which case you don't have space for new files, only for those already there. Check "df -i". Otherwise check the ERRORS section at "man 2 open".

**Comment by Skeddie** [comment]
Closing this as reporter is unresponsive and symptoms seem to indicate a shortage of inodes.
