### ISSUE TITLE
Maybe these should be updated too, is it possible?

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#31]
`site change username wkly_allotment [Num,Num]` 

Instead of default KiB maybe refer to glftpd.conf setting or make it possible to manually set it in MiB/GiB/TiB when command is issued? Like this maybe:

`site change username wkly_allotment 0,2000` for section 0 with 2000KiB 
`site change username wkly_allotment 0,2000M` for section 0 with 2000MiB 
`site change username wkly_allotment 0,2000G` for section 0 with 2000GiB
`site change username wkly_allotment 0,2000T` for section 0 with 2000TiB

Then we have these that are in KiB/s

`site change username max_dlspeed [Str]`
`site change username max_ulspeed [Str]`

Instead of default KiB/s maybe refer to glftpd.conf setting or make it possible to manually set it in MiB/s & GiB/s when command is issued? Like this maybe:

`site change username max_dlspeed 2` for 2KiB/s
`site change username max_dlspeed 2M` for 2MiB/s
`site change username max_dlspeed 2G` for 2GiB/s
`site change username max_ulspeed 2` for 2KiB/s
`site change username max_ulspeed 2M` for 2MiB/s
`site change username max_ulspeed 2G` for 2GiB/s

**Comment by teqnodude** [comment]
This should be updated to a larger size as well.

In olddirclean2.c
`#define MAXDIRLOGSIZE 10000`
Instead set it to
`#define MAXDIRLOGSIZE 1000000`

**Comment by glftpd** [comment]
Updated the site change to allow passing XX[m/gt]. Please test the next release !
