### ISSUE TITLE
fyi, site pre not working in 2.10 static version

### ISSUE THREAD

**Issue by Termin8or666** [glftpd/glftpd#33]
550 ASSERT: (srclen + 1 <= dest_size) in file ftpcmd.y line 3613 inside function gl_strcpy_internal

**Comment by teqnodude** [comment]
Works just fine for me with foo-pre on one of my sites using glftpd-full-static

**Comment by Termin8or666** [comment]
its just happening with long release names

**Comment by teqnodude** [comment]
I tried with a release name that had 169 chars in length and didn't get the error you describe under Debian with glftpd-full-static.

**Comment by Termin8or666** [comment]
Glftpd devs have a fix for this dont know the details but works fine on debug version

**Comment by Termin8or666** [comment]
I have a cscript making the pred dir read only, maybe thats the trigger

**Comment by glftpd** [comment]
yeah i see there is a bug in 2.10 with cscript. for pre you should anyway just use site_cmd so please use that for now. Will be fixed in next version.
