### ISSUE TITLE
glftpd crashes when adding multiple ip's at once and first one leads to auto-removing useless ip

### ISSUE THREAD

**Issue by endgame4** [glftpd/glftpd#34]
Tested on 2.08, 2.09, 2.10 and 2.10a. All have the same result.

When you add multiple IP's at once using 'site addip', and the FIRST one leads to the action 'Auto-removing useless IP', glftpd crashes.

Test steps (5. has the actual problem, 3. an unwanted message):

1. adding complete ip to user:

`site addip user *@1.2.3.4`

> 200- IP '*@1.2.3.4' successfully added to user.
> 200 Command Successful.

result: no problem

2. adding less specific version of already added ip to user:

`site addip user *@*.2.3.4`

> 200- Auto-removing useless IP '*@1.2.3.4'...
> 200- IP '*@*.2.3.4' successfully added to user.
> 200 Command Successful.

result: no problem

3. restoring previous situation:

`site delip user *@*.2.3.4`

> 200- IP (*@*.2.3.4) removed from user.
> 200 Done

result: no problem in ftp client, however this message in error.log: 

`Tried to add an invalid IP or DNS entry to the userfile for user:`

4. re-adding complete ip to user (same as step 1.):

`site addip user *@1.2.3.4`

> 200- IP '*@1.2.3.4' successfully added to user.
> 200 Command Successful.

result: no problem

5. **adding multiple ip's at once and first one leads to auto-removing useless ip**:

`site addip user *@*.2.3.4 *@4.3.2.1`

No output in ftp client.

Following message in /glftpd/ftp-data/logs/error.log: 

`ERROR : glftpd crashed while processing site addip user *@*.2.3.4 *@4.3.2.1 !!! please report this to the developers ASAP`

6. adding multiple ip's at once and first one does not lead to auto-removing useless ip:

`site addip user *@4.3.2.1 *@*.2.3.4`
> 200- IP '*@4.3.2.1' successfully added to user.
> 200- Auto-removing useless IP '*@1.2.3.4'...
> 200- IP '*@*.2.3.4' successfully added to user.
> 200 Command Successful.

result: no problem

**Comment by glftpd** [comment]
thx, will be fixed in next release
