### ISSUE TITLE
wrong nuke calculations / announces on 2.10a

### ISSUE THREAD

**Issue by Termin8or666** [glftpd/glftpd#36]
when a 1556.3MB rls is nuked 3x bot announces 1556.3MB nuked
output in client is this:
 [L] 200- Nukee(s): 2         Files: 35          Total bytes: 1,631,920,590
 [L] 200- -------------------------------------------------------------------------
 [L] 200- Nukee: exampleuser          Bytes: 1556.3MB     Credit Lost: 7781.6MB

**Comment by glftpd** [comment]
which part is wrong ? :)

**Comment by Termin8or666** [comment]
here you see a 1x nuke but the nuke is 3x

[17:37:15] [L] site nuke test 1 test
[17:37:16] [L] 200- Nuke Completed.
[17:37:16] [L] 200- -------------------------------------------------------------------------
[17:37:16] [L] 200- Nukee(s): 1         Files: 81          Total bytes: 11,833,749,076
[17:37:16] [L] 200- -------------------------------------------------------------------------
[17:37:16] [L] 200- Nukee: test        Bytes: 11285.5MB     Credit Lost: 33856.6MB
[17:37:16] [L] 200- -----------------

I can confirm that the credits lost is the amount removed from user.. 

the announce on irc seems to always announce 1x no matter what multiplier is used

**Comment by teqnodude** [comment]
I had an user recently reporting this that confirm that nukes are not done correctly.

```
before nuke [Credits: 7.1GiB]
NUKE: -GAMES- releasename was nuked factor x1 by glftpd [reason] nuke_reason
NUKE: [nukees] user1 (24080.3MB)......
after nuke [Credits: -68.0GiB] 
```

The above shows that user1 had 7.1GB of credits and got nuked 1x with 24080.3MB and ended up with -68GB of credits which is a loss of roughly 75GB of credits which is 3x the amount he was supposed to have lost.

**Comment by glftpd** [comment]
my understanding is that nuking 1x should remove 3x credits if the ratio of the section is 3x... for the upload he did recieve 3x credits too right ?

**Comment by teqnodude** [comment]
glftpd, you are correct of course, guess my thinking was off here and I honestly didn't double check the manual before commenting. I honestly thought 1x were only gonna remove the exact amount they uploaded meaning if they uploaded 1GB it should only be removed 1GB from credits with a 1x multiplier, I never knew that ratio was part of the equation.

**Comment by teqnodude** [comment]
That however doesn't explain the announce `NUKE: [nukees] user1 (24080.3MB)` when it should have been 3x that amount 3+1-1 x 24080.3MB = 72240,9MB. Guess things are not written down correctly into glftpd.log which adds to this confusion.

**Comment by Termin8or666** [comment]
The announce is confusing even if its just the amount they uploaded,
Her you have an example with 2 ratio users and 1 leech.. the leech user also uploaded files but output for him is 0MB (ofc he did not loose any creds as he has unlimited) but then again I think the other output should be credits lost and not the amount they uploaded.
[Nukees] user1 (21.1MB), user2 (13.1MB), user3 (0.0MB).

**Comment by Termin8or666** [comment]
Seems like the 0mb output was related to a corrupt userfile or something. other leechers output the amount uploaded.
Anyway could this be a configurable feature?
Show nukes as size or credits lost?

**Comment by teqnodude** [comment]
I would strongly recommend a change here where the nuked amount/lost credits are written down to glftpd.log instead of uploaded amount since the nuked amount/lost credits is of greater relevance.

**Comment by PatriotM** [comment]
i can confirm that in all versions after 2.10x the nukes are not removed from the stats.
is it possible to bring a fix in time?

**Comment by glftpd** [comment]
im not aware of any case where stats are not removed. i dont think thats what this ticket is about (here we found out everything works correctly) so make a new ticket and describe how to replicate
