### ISSUE TITLE
Feature Request: Support for external ls/listing binary

### ISSUE THREAD

**Issue by sirmarksalot** [glftpd/glftpd#38]
The main reason for the feature request is because of slow listing times for via glftpd when a dir containing a very large number of symlinks (Music archive sorted via audiosort from pzsng is 1 example).

My test example dir is as follow.
1 dir containing 148,000 valid symlinks (invalid symlinks list much faster)
symlinks point to real release dirs mounted from a LAN raid volume via cifs

issuing `time ls` inside the index dir takes more than 5minutes to reply.
getting a reply via glftpd is nearly impossible because of connection timeouts

I quickly made some changes to ls.c from coreutils.
I changed the following lines to false
https://github.com/coreutils/coreutils/blob/master/src/ls.c#L1654
https://github.com/coreutils/coreutils/blob/master/src/ls.c#L1661

After this change the time to list my test dir of 148,000 symlinks was reduced to 2.593 seconds

It would also be nice if option `lslong` was controllable per path like post-check is.

**Comment by sirmarksalot** [comment]
When listing from shell using `ls --color=never` resolves the issue of slow listing.

A option to disable checking the validity of symlinks would be a new feature in glftpd and would be a lot easier to implement than my original proposed feature request

**Comment by sirmarksalot** [comment]
When listing from shell using ls --color=never resolves the issue of slow listing.

A option to disable checking the validity of symlinks would be a nice feature in glftpd and would be a lot easier to implement than my original proposed feature request

**Comment by glftpd** [comment]
hm is it really just gl checking the validity ? isnt it trying to measure the size of the directories or something ? use_dir_size is disabled on the directory ?

Just to make sure, can you do a strace and see what gl is doing to the symlink ? poke me on efnet if you want and we can try to prototype some quick fix

**Comment by sirmarksalot** [comment]
use_dir_size is not enabled.

I see the issue now it's actually from CWD and not the actual listing.

Using `stat -al` with full path results in quick listings when issued from rootfs.

`cwd /archive/mp3-index/group/GRP` does the following.
```
chdir("/site/archive/mp3-index/group/GRP") = 0
getcwd("/site/archive/mp3-index/group/GRP", 4096) = 35
getcwd("/site/archive/mp3-index/group/GRP", 4096) = 35
openat(AT_FDCWD, ".message", O_RDONLY)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, ".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFDIR|0777, st_size=3547136, ...}) = 0
getdents64(6, /* 419 entries */, 32768) = 32744
stat(".", {st_mode=S_IFDIR|0777, st_size=3547136, ...}) = 0
stat("..", {st_mode=S_IFDIR|0777, st_size=77824, ...}) = 0
stat("Music-GRP", {st_mode=S_IFDIR|0777, st_size=77824, ...}) = 0
```

it calls `stat` for each release inside the `/site/archive/mp3-index/group/GRP` dir which ends up taking a very long time when symlinks point to releases on remote mounts

**Comment by sirmarksalot** [comment]
This issue has been resolved by disabling `show_totals` in glftpd.conf

Thanks @glftpd for the assistance in tracking the source of this issue down.
