### ISSUE TITLE
gl_strcpy_internal error

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#39]
i have a problem with long filenames/folders when i create them the error below comes as output and i get a disconnect.

(14:43:01) [2]     MKD title.xxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.LANUGEAGE.SUBBED.YEAR.GENRE.FORMAT.SOURCE.CODEC-GROUP
(14:43:05) [2] 550 ASSERT: (srclen + 1 <= dest_size) in file dirlog.c line 428 inside function gl_strcpy_internal

**Comment by Vunacle** [comment]
I can confirm this issue exist, getting the same error when creating long dirnames/filenames. The error comes around 167-180 chars of dir/filename length. 
Error is : 
"550 ASSERT: (srclen + 1 <= dest_size) in file dirlog.c line 428 inside function gl_strcpy_internal"
And then it disconnects.

**Comment by glftpd** [comment]
fixed in next build
