### ISSUE TITLE
Concurrent command race condition, multiple bugs.

### ISSUE THREAD

**Issue by t-nelson** [glftpd/glftpd#4]
This is with regard to sending a CPSV after ABOR during encrypted file transfer to break the data connection, which is common practice since you can't send the OOB TELNET stuff over an SSL socket.  This behavior isn't actually necessary on modern GL, but I've run into it in the past and noticed it causes some bugs that could crop up in other scenarios.   This will be easiest to explain with some annotated examples.

Both ends are running v2.06.

**Example 1:**

```
I: [0: src(0) > dst(0)]: Sending file: test.rar
D: src(0) <<< CPSV
D: src(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,239,6)
D: dst(0) <<< PORT XXX,XXX,XXX,XXX,239,6
D: dst(0) >>> 200 PORT command successful.
D: dst(0) <<< STOR test.rar
D: dst(0) >>> 150 Opening BINARY mode data connection for test.rar using SSL/TLS.
D: src(0) <<< RETR test.rar
D: src(0) >>> 150 Opening BINARY mode data connection for test.rar (100000000 bytes) using SSL/TLS.
E: [0: src(0) > dst(0)]: transfer_file: select(): Timeout
D: dst(0) <<< ABOR
D: src(0) <<< CPSV
D: src(0) --- Aborting PASV/CPSV used to break SRC data connection.
D: src(0) <<< ABOR
D: dst(0) <<< CPSV
D: dst(0) --- Aborting PASV/CPSV used to break DST data connection.
D: src(0) >>> 500 Unsupported command during transfer.
D: src(0) >>> 426 Transfer aborted. Data connection closed.
D: dst(0) >>> 426 Transfer aborted. Data connection closed.
D: src(0) >>> 226 Abort successful
D: dst(0) >>> 226 Abort successful
D: dst(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,254,118)
W: [0: src(0) > dst(0)]: File action failed! Retrying.
```

Here the file transfer times out and both ends are sent ABOR with an immediate CPSV.  The source site gets the CPSV first and immediately replies with a "500 unsupported".  This is the first bug.  AFAIK, replies should be sent in the order the commands are received.  The behavior exhibited here will break client synchronization as it will interpret the 500 as the reply for RETR, 426 for ABOR and 226 for CPSV.

**Example 2:**

```
I: [0: src(0) > dst(0)]: Sending file: test.rar
D: src(0) <<< CPSV
D: src(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,238,193)
D: dst(0) <<< PORT XXX,XXX,XXX,XXX,238,193
D: dst(0) >>> 200 PORT command successful.
D: dst(0) <<< STOR test.rar
D: dst(0) >>> 150 Opening BINARY mode data connection for test.rar using SSL/TLS.
D: src(0) <<< RETR test.rar
D: src(0) >>> 150 Opening BINARY mode data connection for test.rar (100000000 bytes) using SSL/TLS.
E: [0: src(0) > dst(0)]: transfer_file: select(): Timeout
D: src(0) <<< ABOR
D: dst(0) <<< CPSV
D: dst(0) --- Aborting PASV/CPSV used to break DST data connection.
D: dst(0) <<< ABOR
D: src(0) <<< CPSV
D: src(0) --- Aborting PASV/CPSV used to break SRC data connection.
D: src(0) >>> 426 Transfer aborted. Data connection closed.
D: src(0) >>> 226 Abort successful
D: src(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,239,48)
D: dst(0) >>> 500 Unsupported command during transfer.
T: dst(0) >>> 226-
T: dst(0) >>> 226- | - CRC-Check: BAD!
T: dst(0) >>> 226-
T: dst(0) >>> 226- Checks completed in 0.061269 seconds.
T: dst(0) >>> 226- [Ul: 3280712.5MB] [Dl: 44731.0MB] [Speed: 8633.96K/s] [Free: 3015587MB]
D: dst(0) >>> 226  [Section: DEFAULT] [Credits: 139475.8MB] [Ratio: Unlimited]
D: dst(0) >>> 225 ABOR command successful.
E: [0: src(0) > dst(0)]: File action failed! Giving up!
```

This example is the same as the first, except that the destination site gets CPSV first.  Here, along with the out of order CPSV reply, we get the second bug that the (intended) STOR reply is 226 rather than the correct 426.  The file on the source is known good, so if this were in fact the case that the transfer completed before the server serviced the ABOR -- as implied by the (intended) ABOR reply of 225 -- the CRC check would have passed.  Instead, I suspect that since the source has already closed the data connection, GL is misinterpreting the current state of the transfer.

**Example 3:**

```
I: [0: src(0) > dst(0)]: Sending file: test.rar
D: src(0) <<< CPSV
D: src(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,238,117)
D: dst(0) <<< PORT XXX,XXX,XXX,XXX,238,117
D: dst(0) >>> 200 PORT command successful.
D: dst(0) <<< STOR test.rar
D: dst(0) >>> 150 Opening BINARY mode data connection for test.rar using SSL/TLS.
D: src(0) <<< RETR test.rar
D: src(0) >>> 150 Opening BINARY mode data connection for test.rar (100000000 bytes) using SSL/TLS.
E: [0: src(0) > dst(0)]: transfer_file: select(): Timeout
D: dst(0) <<< ABOR
D: src(0) <<< ABOR
E: [0: src(0) > dst(0)]: transfer_file: Timeout waiting for reply.
D: dst(0) <<< CPSV
D: dst(0) --- Aborting PASV/CPSV used to break DST data connection.
D: src(0) <<< CPSV
D: src(0) --- Aborting PASV/CPSV used to break SRC data connection.
D: src(0) >>> 426 Transfer aborted. Data connection closed.
D: src(0) >>> 226 Abort successful
D: src(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,238,189)
D: dst(0) >>> 426 Transfer aborted. Data connection closed.
D: dst(0) >>> 226 Abort successful
D: dst(0) >>> 227 Entering Passive Mode (XXX,XXX,XXX,XXX,254,73)
W: [0: src(0) > dst(0)]: File action failed! Retrying.
```

The final example confirms the race condition.  Here both sites are sent ABOR, the client select()s on the control sockets for 50ms, then sends both sites CPSV.  In this case all commands and replies are as expected.

It should be noted here that the file transfer "timeout" in these examples has nothing to do with the data connection or any network issues.  Instead, select() is called on the control sockets with an intentionally short timeout.  So this is closer to a user cancelled transfer.

**Summary**
1. There is a race in the handling of concurrent commands
2. The reply for unsupported concurrent commands is sent out of order
3. Aborting the receiving end of a transfer in such a manner as to trigger 1 and 2 results in an incorrect reply

**Comment by glftpd** [comment]
thx ill check if its something that can be easily fixed

**Comment by glftpd** [comment]
Actually there is no race. Its just how things are implemented.

For case 1) if a client sends CPSV first during the transfter the code doesnt really have a good way to handle it and just throws out the reponse right away. This is arguable if its correct or not but for example if you send STAT during transfer we also give you the answer right away and out of order of the commands. Its quite possible the behaviour is wrong but implementing something that stores the replies and writes them after the transfer is i think not worth it. The scenario when client inside STOR/RETR sends first CPSV and then ABOR is i think just a bad client behaviour as ABOR should be first and CPSV should only come if we are not inside STOR/RETR.

For case 2) it seems src was able to handle the ABOR first so it closed connection to dst and dst handled the file transfer end the usual way (conn was closed so we check the file content etc) and only then tried to ABOR which didnt do anything and just printed standard reply.

**Comment by t-nelson** [comment]
Point taken WRT sending CPSV before ABOR.  I had overlooked that detail when reusing my ABOR code for when transfer initiation fails.

I will have to check the RFC so far as proper behavior when an unsupported command is encountered during transfer.  Odds are it isn't addressed at all. :)

I agree with your analysis of Example 2.  The issue was that dst returns a 226 for the aborted STOR command, where it should be a 426.  The dst ABOR reply is the correct 225 since the data socket was already closed (ending the transfer) by the src, hence the 226 ABOR reply on the src.
