### ISSUE TITLE
Switch transfer time in xferlog from seconds to milliseconds

### ISSUE THREAD

**Issue by BaneHardy** [glftpd/glftpd#40]
Title says it all. Please provide a switch in glconf that changes transfer times in xferlog from seconds to milliseconds. Seconds are not sufficient for todays transfer speeds. Especially for smaller files on 1 gbps or usual file sizes on link speeds above 1 gbps.

**Comment by ZarTek-Creole** [comment]
+1

**Comment by glftpd** [comment]
Added '-m' glftpd switch to change xferlog times to miliseconds. Didnt do much testing so please check :)
