### ISSUE TITLE
How are glftpd 2.01 hashes computed?

### ISSUE THREAD

**Issue by maltris** [glftpd/glftpd#41]
Hello,

for a migration from glftpd to proftpd (its better suited, easier to administer and GPL licensed), I am trying to migrate the glftpd hashes over to the newer proftpd setup, but struggle with the compatiblity as I am not 100% sure on how the password hashes of glftpd 2.01 are computed.

I created a related question on serverfault with most of the details:

https://serverfault.com/questions/1010310/migration-of-password-hashes-from-glftpd-2-01-pkcs5-pbkdf2-hmac-sha1-to-proftp

Can you give a quick walkthrough on how the hashing is done, so I can try to reproduce the very same process with proftpd to be able to migrate successfully?

**Comment by glftpd** [comment]
which part isnt clear ? you found the password sample code and the documentation for the openssl function is here https://www.openssl.org/docs/man1.1.0/man3/PKCS5_PBKDF2_HMAC_SHA1.html

**Comment by maltris** [comment]
Thanks for your friendly answer, it is all clear now.
