### ISSUE TITLE
2.11 beta dirlog bug

### ISSUE THREAD

**Issue by Termin8or666** [glftpd/glftpd#42]
after upgrading to 2.11 the dirlog does not update.
Ive seen the problem on atleast 6 sites.
If tur-dirlogclean.sh is called manually it will update the dirlog so seems like the new changes in 2.11 does not pass to dirlog on uploads

**Comment by glftpd** [comment]
and it works fine in 2.10a ?

**Comment by glftpd** [comment]
will be fixed in next beta/release
