### ISSUE TITLE
pasv_addr round robin issue

### ISSUE THREAD

**Issue by Vunacle** [glftpd/glftpd#43]
Tested with versions 2.10a,2.11beta1

I have noticed an issue with the round robin feature in regard to using pasv_addr in config.

From docs:
"If you have multiple pasv_addr lines, glftpd will cycle through them in
a round-robin style each time a file is transferred using passive mode."

In direct assign interface (pasv_addr xxx.xxx.xxx.xxx), it round robin the pasv_addr on each file.

But When using pasv_addr in "nat" mode (pasv_addr xxx.xxx.xxx.xxx 1). where it report a different ip to the client than the ip of the interface it binds to, it does not round robin on each file.
Using this option it round robin on a per session basis, so all transfered files within this session uses the same pasv_addr that was selected during connection of the session.

Example would be like:
pasv_addr xxx.xxx.xxx.1xx 1
pasv_addr xxx.xxx.xxx.2xx 1

When connecting it select one of these pasv_addr, and continue to use that for the remainder of the session for all files. 

Per session is not very effective as load-balance, compared to per file. 

Hope someone have the answer to this.

**Comment by glftpd** [comment]
Brief look at the code shows this should work. can someone else confirm this doesnt work and is easy to replicate ? With just some simple test ?

**Comment by Vunacle** [comment]
Thank you for the reply.

The easiest way I can think of to reproduce this issue is by adding 2 pasv_addr lines like this:

For ease let us say the server address is 10.0.1.10

pasv_addr 10.0.1.10
pasv_addr 10.0.2.10 

(This will of cause give a error that it cannot assign the 10.0.2.10 address each time it hits that.)

Doing a pasv transfer will show it round-robin these 2 addresses at each file it transfers, giving the "cannot assign.." every 2nd file.

The issue then comes if we add the "1" option at the end to the 2 lines.

pasv_addr 10.0.1.10 1
pasv_addr 10.0.2.10 1

Now it will select one of these pasv_addr at connect, and stay on that for the duration of the session.
If it selects 10.0.1.10 at connect, all files will be transfered using this address and no errors.
If it selects 10.0.2.10 at connect, all files will give an error that it cannot assign requested address, showing it uses the same address for all files, else this error would only come every 2nd file.

Hope this is helpful and might explain it  better.

**Comment by glftpd** [comment]
thanks ill try hopefully soon :)

**Comment by glftpd** [comment]
ok can confirm its easy to replicate
