### ISSUE TITLE
glFTPd Stats (v2.3)

### ISSUE THREAD

**Issue by superexony** [glftpd/glftpd#44]
In glFTPd Stats (v2.3) option -o <group> doesnt work anymore, still shows all groups.

works fine in Stats (v2.1)

**Comment by teqnodude** [comment]
Running `./stats -m` show all stats in zero at the same time as `site monthup` show correct stats on a site running glftpd-LNX-2.11_BETA3

**Comment by glftpd** [comment]
should be fixed in the next version
