### ISSUE TITLE
site_cmd custom-command character length limitation

### ISSUE THREAD

**Issue by Bsugar9** [glftpd/glftpd#46]
doing in glftpd.conf :

BAD
site_cmd symlink-movies EXEC /bin/scripts/bs-symlist-movies.sh
custom-symlink-movies *

Will cause the glftpd.conf not to load.
There is a character length limitation of 12 characters on this function.  It isn't documented. 
Would be nice to increase the amount of characters in site_cmd

GOOD
site_cmd linkmovie EXEC /bin/scripts/bs-symlist-movies.sh
custom-linkmovie *

**Comment by glftpd** [comment]
Currently the maximum keyword length inside glftpd.conf is 19 which is why custom-symlink-movies is refused by the parser.

**Comment by glftpd** [comment]
improved in next version
