### ISSUE TITLE
ABOR command returns 435 during FXP of existing files

### ISSUE THREAD

**Issue by pr-svg** [glftpd/glftpd#47]
Hello,
I have version 2.10a.
I notice a problem with FXP and ABOR. The problem happens with the source GLFTPD server when I try to send files that already exist on the target:
1. send CPSV to target
2. send PORT to source
3. send RETR to source
4. send STOR to target
5. target replies with 553 This file looks like a dupe
6. send ABOR to source

All this works well the first time: the source sends 
```
426 Transfer aborted. Data connection closed
226 Abort successful
```

But if I do the same thing one more time, I get
```
435 Failed TLS negotiation on data channel (Already TLS connected!), disconnected
225 ABOR command successful.
```

After this, it is impossible to do any RETR command on the source, I get error 435 again. I have to disconnect and reconnect.

This is very easy to reproduce the bug with the lftp client:
* connect to a FTP server that supports CPSV
* `set ftp:ssl-protect-fxp true`
* `put ftp://glftpd/path/to/file` # create the file
* `put ftp://glftpd/path/to/file` # the file exists, lftp sends ABOR and I get 426+226
* `put ftp://glftpd/path/to/file`# now I get 435+225
* `rm file`
*  `put ftp://glftpd/path/to/file`# I can't even send the file now

**Comment by glftpd** [comment]
Thanks for the report. I was actually trying to find out whether the "already tls connected" issue was related to ABOR since we have seen it happen sometime in the old versions.

As I rewrote most of the data connection handling could you please check with version 2.11b3 to see if its any different there ?

**Comment by glftpd** [comment]
I did a brief test and while the issue seems fixed i ran into an assert that timeout handler wasnt properly cleaned up. So at least something to fix :)

**Comment by pr-svg** [comment]
Yes, the beta completely fails when I send ABOR the second time, I get `550 ASSERT: (toolong_old_alarm == -1) in file alarm.c line 112 inside function init_toolong` instead of error 435.

I will wait for a fix.

**Comment by pr-svg** [comment]
@glftpd Do you think there is a workaround for older versions?

**Comment by glftpd** [comment]
not sure if some workaround would be possible, i guess it somehow messes up the state of the connection in 2.10, thats why i rewrote it in 2.11, unfortunately i messed up the timeout handling but i have it fixed locally for next release at least

for 2.10 you  might need to reconnect... but feel free to try to reissue PROT or PASV/PORT etc to see if any fixes it...
