### ISSUE TITLE
Support for graceful termination of transfers via external speed kicking 

### ISSUE THREAD

**Issue by ty1erdurd3n** [glftpd/glftpd#48]
Today, many sites employ external speed kick scripts, that kill glftpd to abort transfers it decides are too slow.

This has many issues, from race-conditions where glftpd is killed as the zipscript runs, to wasted time/resources when the client needs to reconnect to start a new transfer.

This suggestion is for a new signal handler in glftpd that would allow an external speedkicker to tell glftp to gracefully terminate a file transfer and allow the client to stay connected.

When glftp receives this signal and the user is uploading, it should:

1) delete the file
2) not run the zipscript
3) undupe the file
4) gracefully close the data connection
5) log to glftpd.log
6) sleep a configurable amount of time (configurable via new variable in glftpd.conf)
7) tell the user "452 transfer terminated by external program", or something similar (configurable via glstrings)
When glftp receives this signal and the user is downloading, it should:

1) gracefully close the data connection
2) tell the user "452 transfer terminated by external program", or something similar (configurable via glstrings)
3) log to glftpd.log

The signal should be ignored if no transfer is ongoing.

This solution has been discussed with @steakboy7000 (cbftp) and xerox (slftp) who both think its a good idea! :)

**Comment by teqnodude** [comment]
Here is an idea. One could consider the option to build it as a feature of glftpd where it is disabled by default with various settings in glftpd.conf. That would remove the necessity of external programs and maybe it could be an easier way of controlling a graceful termination of a transfer because of slow speed.

**Comment by glftpd** [comment]
Kindof like the idea so added handler for SIGUSR1 that does hopefully all you asked for. Please test in next version :)

**Comment by glftpd** [comment]
Btw didnt implement the logging to glftpd.log. Not really sure it belongs there.
