### ISSUE TITLE
site ratio command with primary groups

### ISSUE THREAD

**Issue by h-0-s-h** [glftpd/glftpd#5]
Issue:  If you are a GADMIN of a group, you should  be able to change the ratio of ANY user in any of your subsequent GADMIN(ed) groups.  Currently it won't allow you to do site change ratio unless your GADMIN group is a common "Primary"

From the glftpd.docs:

> Note: by default, gadmins have access to the following commands:
>     -addip, -adduser, -changeratio, -chpass, -delip, -deluser,
>     -flags, -ginfo, -grpnfo, -readd, -userextra, -grp.
>     **_These commands are gadmin-restricted, meaning that if you are a
>     gadmin you can only use those commands on users who are in the 
>     same group as your first (primary) group._**  Other commands are
>     not gadmin-restricted, so if you give gadmins access to them, they
>     will be able to use them on ANY user.

With certain site configurations, some gadmins don't want their group to be primary, they would rather mask their group so that no one knows which group they belong to.
This makes it so that if their GADMIN group is secondary, the gadmin commands won't work.
Giving them access to -changeratio is a bad idea for obvious reasons...

**Comment by Skeddie** [comment]
Thanks for reporting, this will be investigated. No ETA at the moment but a comment will be placed when news is available.

**Comment by Skeddie** [comment]
I have tested this on the last 2.07BETA2 by first logging in with siteop account and doing:
- site grpadd Primary
- site grpadd Secondary
- site gadduser Primary sgadmin sgadmin *@localhost
- site chgrp sgadmin Secondary
- site chgadmin sgadmin Secondary
- site gadduser Secondary suser suser *@localhost
- site grpchange Secondary leech_slots 2
The last is needed to be able to change from (my) default ratio 1:3.
Then I logged in with the gadmin account and issued:
- site ginfo #To verify ratio 1:3 on suser and free leech slots
- site change suser ratio 0
Issuing "site ginfo" again shows me the ratio of suser changed to leech.

Then I tested some more with siteop doing:
- site chgrp suser Primary
- site chpgrp suser Primary
And then logging back in as sgadmin I could without a problem change the ratio.

And to complete it, siteop doing:
- site chgrp suser Primary
- site grpadd OtherPrimary
- site chgrp suser OtherPrimary
- site chpgrp suser OtherPrimary
And again, sgadmin could problemless change the ratio.

So, what am I missing? And no, my "-change" setting in glftpd.conf is default "1 7" and "-changeratio" default "1 2 7".

**Comment by Skeddie** [comment]
Closing as no more feedback from the reporter and issue can not be reproduced. Might need a docs update removing the "first (primary)".
