### ISSUE TITLE
website forbiden links

### ISSUE THREAD

**Issue by sachaz** [glftpd/glftpd#50]
Hi,

on the website gltpd.io, 403 for:

- https://glftpd.io/beta/docs/README.IPv6
- https://glftpd.io/beta/docs/

**Comment by teqnodude** [comment]
Should be
https://glftpd.io/files/docs/README.IPv6
https://glftpd.io/files/docs/

**Comment by sachaz** [comment]
yes, that's not the links on the Documentation part of the gltpd.io site

**Comment by glftpd** [comment]
should be fixed now, thx

**Comment by sachaz** [comment]
thanks !
