### ISSUE TITLE
truncated nfos

### ISSUE THREAD

**Issue by joebar98** [glftpd/glftpd#52]
Since 2.11 betas, some nfo files transferred between glftpd sites are truncated. This is still present in 2.11 final. I've attached a typical ascii art truncated in the new gl. File was transferred in ascii mode using flashfxp, no ssl, using FreeBSD 2.11 x64 on FreeBSD 12.1

[nfo-issue.zip](https://github.com/glftpd/glftpd/files/5746577/nfo-issue.zip)

**Comment by glftpd** [comment]
Could you please test this build ?
The new buffer code had a bug with handling unsigned chars and when nfo contained 0xff byte it would end the ascii transfer.

https://glftpd.io/files/dev/glftpd-LNX-dev_1.1.1i_x64.tgz

**Comment by joebar98** [comment]
sorry, like I've put in my req, I use FreeBSD :(

**Comment by glftpd** [comment]
sorry, https://glftpd.io/files/dev/glftpd-FBSD-dev_1.1.1i_x64.tgz

**Comment by joebar98** [comment]
so far so good!
