### ISSUE TITLE
FreeBSD /usr/local/etc/glftpd.conf

### ISSUE THREAD

**Issue by sachaz** [glftpd/glftpd#53]
Hi,

as discussed on irc:

In case of an install with a chroot (called jail on the Glftpd install): /etc/glftpd.conf should be: /usr/local/etc/glftpd.conf

here is a diff from install.sh for a simple patch:

```
root@gl:~ # diff glftpd-FBSD-2.11_1.1.1i_x64/installgl.sh glftpd-FBSD-2.11_1.1.1i_x64-0/installgl.sh
631a632,634
>     if [[ $os = freebsd* ]]; then
>         confdir="/usr/local/etc"
>     fi
```

**Comment by glftpd** [comment]
thx, done
