### ISSUE TITLE
performance killer and pointless hdd load (recursive listmode)

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#55]
it would be great if you could disable the recursive list mode. since it only costs performance.

there are probably still more possibilities with mode "R" so it would be great if you could activate standard types as is the case with SSL. from to

command as example: STAT -Ral

note:

I tested it and it didn't work for me "lslong"

**Comment by glftpd** [comment]
do i understand it right its slow if some user uses -R and the whole feature should be configurable ?

im not sure what the rest of the issue is about with STAT and SSL ?

**Comment by PatriotM** [comment]
there are some people who use this recursive listing, this is of course rather unfavorable if they do it in the root directory then the whole list goes over all sections and the load of the server goes up to the immeasurable.

thus pointless queries are generated and the hard disks work. because someone does not have his ftp client under control. it would be great if you could turn it on and off.

**Comment by glftpd** [comment]
Hm should it return an error or just ignore the switch ? What would break the clients less ? Can you check with whoever uses that command ? :)

**Comment by PatriotM** [comment]
it would be good if you can set the option to turn it on or off in glftpd.conf

maybe there are people who need this option?

if you disable it, maybe the solution would be to get into the default stat -l mode or list. also this would be surely good for the glftpd.conf

that you can choose how the input list is and which it can be replaced by, as well as an on and off option for recursive

maybe switch?

0 ignore
1 on
2 off
3 replace in list
4 replace in stat -l (instead of stat -R)

**Comment by glftpd** [comment]
I would only go for something simple. I guess something like "ignore_recursive_dirlist 1" would completely ignore the -R.

**Comment by glftpd** [comment]
added "ignore_recursive_dirlist 0/1"
