### ISSUE TITLE
"ghost" 0byte bug still there on 2.11a

### ISSUE THREAD

**Issue by zx6r2** [glftpd/glftpd#58]
H gl dev team

I do continue to observe 0byte files on version 2.11a. 
A similar (same?) issue was already discussed as bug #28 which was said to be fix in 2.10 but apparently it is still there, at least as a   corner cases which do create the issue.

The issue looks:
- existing for quite a long time in GL
- to be highly random with no clear reproduction steps.
- to happen more frequentl with multiple concurrent uploads
- could be linked to TLS errors
- when it does happen the glftpd process tends to use 100% of CPU (TBC)

0byte file is not logged anywhere its like the connection never occurred.
the upload a stalled on the user ftp client
the 0byte file can be removed by kicking the user from the site or by idletimeout of the session.

scenario is:
Fri Jul 16 06:37:53 2021 [591608  ] command: PORT A,B,C,D,78,54
Fri Jul 16 06:37:54 2021 [591608  ] command: STOR myfile.r13

and then nothing more
- no TCP connection toward A.B.C.D:(78*256+54) found
- client is blocked in STOR state
- file is 0byte on the filesystem

reproduced on the 3 bin:  glftpd, glftpd-full-static and glftpd-full-dynamic

The issue  is not new but it would be great to fix it as it does create a lot of issues (slowness, kicks, reconnect).

Could you have a look 

Good work on the upcoming version as always

**Comment by glftpd** [comment]
Please see if you can make a dump of the process when it gets into such state that it hangs with a 0byte file and its eating 100% cpu. maybe ill be able to find something from it.

**Comment by glftpd** [comment]
fixed one issue with active_addr/pasv_addr load balancing that caused hang during transfer
