### ISSUE TITLE
question about character conversions flags and excludes

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#59]
file_names      0               lower
#dir_names      1               none            [:space:]_

is it possible that you can enforce users/groups/rights. by default it is only possible that all are affected by this rule. almost on or off, but it would be great if you could maybe exclude users from it. so that one could separate this e.g. siteops would be excluded from this rule.

**Comment by glftpd** [comment]
would be also nice to configure it per directory

maybe next year :)

**Comment by glftpd** [comment]
done
