### ISSUE TITLE
Changing to a non existing directory successful !?

### ISSUE THREAD

**Issue by lolomin** [glftpd/glftpd#60]
Using glftpd-LNX-2.12_3.0.1_x64 here and discovered this strange behavior : 

ncftp> open -u webcam -P 44444 192.168.0.1
Connecting to 192.168.0.1...
Cygnus-FTP-Server (glFTPd 2.12 (Dec 25 2021) 64BiT Linux+TLS(OpenSSL 3.0.1 14 Dec 2021)+SSP) ready.
Logging in...
Password requested by 192.168.0.1 for user "webcam".

    Password required for webcam.

Password: ********
...
User webcam logged in.
Logged in to 192.168.0.1.
ncftp / > ls -al
total 355
drwxrwxrwx  12 webcam   WaReZ        4096 Jan  2 12:33 .
drwxr-xr-x  19 glftpd   glftpd       4096 Jan  1 15:08 ..
drwxr-xr-x   2 glftpd   glftpd       4096 Dec 18 07:00 .well-known
drwxrwxrwx   6 webcam   WaReZ        4096 Jan  2 12:22 Escalier
drwxrwxrwx   4 430      glftpd       4096 Feb 24  2021 Exterieur_Arriere
drwxrwxrwx   4 webcam   WaReZ        4096 Jan  2 00:02 Exterieur_Avant_Bas
drwxrwxrwx   4 webcam   WaReZ        4096 Jan  2 12:52 Exterieur_Avant_Haut
drwxrwxrwx   4 webcam   WaReZ        4096 Jul 26  2017 FI9828P_00626E6468FD
drwxrwxrwx   7 48       glftpd       4096 Jan 25  2021 Maman_Backups_Orion
drwxrwxrwx   4 webcam   WaReZ        4096 Jan  2 12:42 RDC
drwxr-xr-x   5 glftpd   glftpd       4096 Dec 27 20:09 _OLD
lrwxrwxrwx   1 glftpd   glftpd         12 May 28  2021 _h5ai -> _h5ai-0.30.0
drwxr-xr-x   4 48       glftpd       4096 May 28  2021 _h5ai-0.30.0
-rw-------   1 glftpd   glftpd     131803 Jan 24  2021 h5ai-0.30.0.zip
ncftp / > cd 01
 --NEWS--

 New Feature:  Login with (!)Username to kill ghost connections.

 --=- Type SITE HELP for a nice list of SITE commands -=--

 Jumped To /Exterieur_Avant_Haut/2022
CWD command successful.
ncftp /01 > ls -al
total 16
drwxrwxrwx   2 webcam   WaReZ        4096 Jan  2 12:48 .
drwxrwxrwx   4 webcam   WaReZ        4096 Jan  2 12:52 ..
ncftp /01 > cd 01
 Jumped To /Exterieur_Avant_Haut/2022
CWD command successful.
ncftp /01/01 > ls -al
total 16
drwxrwxrwx   2 webcam   WaReZ        4096 Jan  2 12:48 .
drwxrwxrwx   4 webcam   WaReZ        4096 Jan  2 12:52 ..
ncftp /01/01 > cd toto
Could not chdir to toto: server said: toto: No such file or directory.
ncftp /01/01 > cd 02
 Jumped To /Exterieur_Avant_Haut
CWD command successful.
ncftp /01/01/02 > cd 03
 Jumped To /RDC/2022/01/02
CWD command successful.
ncftp /01/01/02/03 >

Why that ? bug ? wrong configuration somewhere but where ?

Regards,

lolo

**Comment by lolomin** [comment]
Hi,

After searching the cause of this behavior, finally found that it's related to the feature that allow to got immediatly to the recent created directories by CWD XX.

Problem is that some Reolink Cameras are doing some "tests" of the existence of a directory by CWD to a directory for the day (01->31) or month (01 to 12) and if the directory is not existing  (error returned by the CWD command) then creates the directory, with glFTPd this is a problem because CWD is always returning successfull even if the directory is not existing in the current directory and so the upload of a new image/video file is then done on the wrong directory by the Camera :)

Extract of a discussion with @Hujer on EFNet for reference on 04th January 2022 :

[09:40] <lolomin> @Hujer, thks for your answer yesterday, problem with this feature is that some Reolink Cameras are CWD to XX where XX 01 -> 31 to check if the directory exists, if not exist (error returned by CWD) then MKDIR, but with glFTPd since a CWD XX but not existing directory in current dir reports always successful then the upload for a videofile by the camera goes to the wrong directory :/
[14:18] <@Hujer> aha, currently there is no setting to turn that feature off but should be simple to add one, please add the info to the bug you created and ill do it at some point

Maybe a new parameter which will allow to ignore/disable this feature in some specific paths?

Regards,

lolo

**Comment by glftpd** [comment]
added "nonumdir path" that allows you to disable the "cd <number>" feature for any or all paths
