### ISSUE TITLE
xferlog replacing spaces with an underscore on uploads but a questionmark on downloads.

### ISSUE THREAD

**Issue by Turranius** [glftpd/glftpd#62]
(glFTPd 2.12 (Dec 25 2021) 64BiT Linux+TLS(OpenSSL 3.0.1 14 Dec 2021)+SSP)

If a directory has a space in it and you **download** a file, xferlog replaces the space with a questionmark. This is OK

Fri Jan 28 14:39:35 2022 3 IP 3191999 /site/EAB/**Retroplay?WHDLoad?Packs**/Commodore_Amiga_-_WHDLoad_-_Games/E/Elvira_v1.2_NTSC.lha b _ o r USER eabuploader 0 *

That is fine because if we want to actually do something to the dir, we just replace the ? with a space.

The actual path is /site/EAB/**Retroplay WHDLoad Packs**/Commodore_Amiga_-_WHDLoad_-_Games/E/Elvira_v1.2_NTSC.lha

However, when **uploading** to the same directory, it replaces the spaces with an underscore instead, making it quite impossible to get the proper directory.

Fri Jan 28 14:38:31 2022 3 IP 3191999 /site/EAB/**Retroplay_WHDLoad_Packs**/Commodore_Amiga_-_WHDLoad_-_Games/E/Elvira_v1.2_NTSC.lha b _ i r USER eabuploader 0 *

That makes it impossible to replace the _ with a space as it might (and in this example, does) have actual underscores in the directory names.

Could uploads also replace spaces with a question mark in the xferlog instead?
I know this could be "fixed" by replacing spaces with something else in dir_names but this particular FTP is for Retro Amiga and not everything is compressed into archives and needs a space in the directory name.

**Comment by glftpd** [comment]
changed so both cases use '?'
