### ISSUE TITLE
feature request to glFTPd Stats

### ISSUE THREAD

**Issue by ia2115** [glftpd/glftpd#65]
someway to manipulate what glftpd stats outputs:

/glftpd/bin/stats -u -t
                          Today's Top (Up)
--------------------------------------------------------------------------------
 ##  Username                 Tagline               # Files        Size    KiB/s
--------------------------------------------------------------------------------

wanna manipulate what rows are displayed, and not just all as seen here, it possible.

i really dont want tagline here, i want to remove it.
or maybe have a delimiter between each row the i can easy filter out taglines from the wanted outputs.

**Comment by glftpd** [comment]
I think the columns in rows have hardcoded fixed sizes right ? So should be enough to just parse the columns based on that and then show as you like ?
