### ISSUE TITLE
Round robin PASV binding issue

### ISSUE THREAD

**Issue by sirmarksalot** [glftpd/glftpd#66]
Hello, I'm seeing a issue where when using round robin pasv_addr and one of the address is behind a NAT the wrong addr is bound.

```
pasv_addr 1.1.1.1
pasv_addr 2.2.2.2
pasv_addr 3.3.3.3 1
```
when it's 3.3.3.3's turn to be used the PASV reply is correct via the ftp client but glftpd itself open the socket on 1.1.1.1

the 3.3.3.3 ip address is the default gateway for the system while the other two addresses use policy routing

**Comment by glftpd** [comment]
Im not sure what the problem should be. setting "pasv_addr 3.3.3.3 1" means the round robin will report 3.3.3.3 to the client and use whatever next pasv_addr it finds (or ip found from the control connection interface). That seems just right.

What are you trying to achieve that doesnt work ?

**Comment by sirmarksalot** [comment]
note: this is no longer a issue for me as port bonding is now used but this was the issue.

I have 3 ifaces on a linux host.
eth0/1.1.1.1 is a wan address   ```pasv_addr 1.1.1.1```
eth1/1.1.1.2 is a wan address   ```pasv_addr 1.1.1.2```
eth2/192.168.1.3/24 is a NAT address  ```pasv_addr 1.1.1.3 1```

glftpd cycles threw the address' fine as far as the client is concerned (PASV reply has the correct address') but when its eth2's turn to be used for PASV the listen socket is opened on eth0/1.1.1.1 on the host running glftpd when it should be on 192.168.1.3. the pasv Reply from the server shows the current ip 1.1.1.3 port 1111 but the connection fails becasue glftpd opens a socket on 1.1.1.1 port 1111

I realize this is a very uncommon setup but i noticed this issue when i had a network with that unusual setup


edit: come to think of it now i was using policy routing and I'm not sure what ip was the actual main default gw. I'm pretty sure it was the NAT ip's /24 but this setup also caused issues with ```pasv_addr 1.1.1.2``` as only 1 ip would work for pasv.
i believe there is a issue here but I'm not using a setup like this anymore so its too difficult to test so i will just close this issue.
