### ISSUE TITLE
incorrect time display UTC vs CEST

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#68]
in the last stable version the glftpd shows the wrong time of the created files/folders but it should output the locale server time as time attribute, it shows UTC instead of CEST, with the older glftpd versions the display is correct.

timedatectl
               Local time: Fri 2022-08-26 09:43:49 CEST
           Universal time: Fri 2022-08-26 07:43:49 UTC
                 RTC time: Fri 2022-08-26 07:43:49
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: n/a
          RTC in local TZ: no

**Comment by glftpd** [comment]
Very unlikely that something in gl has changed. (unless something in libc changed) Are you sure your /etc/localtime in glftpd chroot is matching your system ?
