### ISSUE TITLE
make dir_names character conversion result available to MKD response

### ISSUE THREAD

**Issue by sky1ab** [glftpd/glftpd#69]
from IRC: 
so in the v1.22 changelog there is this: "The MKD command will now respond with the name of the directory created." 
sadly, the MKD POST script doesn't get that very same information
like, the result of dir_names character conversion

i can't estimate if the file_names conversion result has any impact on anything THAT important

**Comment by glftpd** [comment]
Well the PRE/POST scripts really just get what the client sent without any processing as far as i know. Is there any other case where the POST script gets some additional info ?

**Comment by sky1ab** [comment]
for directories CSCRIPT MKD
and post_check sends filename directory crc32
so this one might be affected by both dir_names and file_names conversion
never tried XMKD

**Comment by glftpd** [comment]
Well post_check is a very different thing from CSCRIPT PRE/POST command. I was wondering if the CSCRIPT ones can be easily extended somehow.

Of course it would be possible to add something like post_dir_check but im not sure if its worth it.

Btw why isnt the pre_dir_check enough for you ?

**Comment by sky1ab** [comment]
The conversion filters allow pretty much any (even stupid) rules, so,
CSCRIPT POST MKD needs to send the final dirname, to get correct data  e.g. into a mysql table.

I do not claim the current behaviour of post_check is wrong, i just mentioned it because you asked for more "cases"
and most probably the dirname sent by post_check is the already-converted-dirname (pwd), same for the filename (untested) 

I assumpt the logfiles (dirlog, dupelog, dupefile, glftpd.log and maybe even xferlog) always contain the final names, 
so it would really be a lot better code design, if the conversion results are not exclusively available for internal routines

----------------------
The pre_dir_check seems off-topic (i thought it runs before the conversion?), 
and post_dir_check sounds like a duplicate for CSCRIPT POST MKD ?

**Comment by glftpd** [comment]
The point im trying to make is that the CSCRIPT feature doesnt actually understand what command is being executed and it just runs your script. So it cannot provide you some additional info like the modified directory name. CSCRIPT just tells you the command and has no further context (as far as i remember there is no CSCRIPT that can provide more info).

post_check, pre_dir_check etc are a different feature where glftpd understands whats happening and run the script and parameters as defined for that concrete situation.

I think the pre_dir_check provides a secondary argument with the modified name.

**Comment by sky1ab** [comment]
So there is currently no function which could tell a external script the final dirname ?
Then, i have to correct myself: the idea of a post_dir_check seems a very good idea indeed.

And yes it's worth it, as long there is no other way to insert correct data into a external database

edit: oh, there is "botscript_path filepath" -- i'll have to test what is sent there

**Comment by sky1ab** [comment]
botscript gets the converted dirnames, so case closed
