### ISSUE TITLE
Can you please add new feature into glupdate.c? Skip processed dirs? Or only process 10,20,30... new dirs?

### ISSUE THREAD

**Issue by scriptzteam** [glftpd/glftpd#7]
So basically i store on server old folders that are empty and everytime i run glupdate it goes thru all those 100000000 of empty folders and updating basically nothing on it :D So can we add some param to do only first newest 10,20,30 etc etc folders ?

Or better tell me how it written into log file, those folders into and i will port it to PHP which is easiest and faster to code :D - I can not figure from that glupdate.c how it is written into dirlog file pls guide me, in dirlog there are some funny strings like "^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@" and a lot!

THX!

**Comment by Skeddie** [comment]
It is recommended to use the far more superior https://github.com/nixnodes/glutil.
