### ISSUE TITLE
botscript parameter $2 problem with special character &

### ISSUE THREAD

**Issue by sky1ab** [glftpd/glftpd#70]
required: add \& to path-filter, or disable path-filter 
1) create a folder containing &, e.g. test&folder
2) folder is created, added to dirlog etc.
3) error.log contains "bad chars in path, not executing botscript. "

A folder "test test test" is sent correct as $2: "/site/test test test" to botscript, so some quoting seems to happen ? 
So, why not send strings containing & in quotes too?

--> Which others characters also trigger this "bad chars in path" ?

BONUS: CSCRIPT MKD POST sends $1: "MKD test&folder" $2: "user"
just passed through, like explained in the other issue
###################
so we're back to: can't reliably add new folders (via shellscript) to mysql
possible solution: post_dir_check like the botscript_path, but without the "bad chars" filter ?

**Comment by glftpd** [comment]
its just some old protection. ill add a switch to turn it off

**Comment by glftpd** [comment]
added botscript_allow_all_characters [0/1]
