### ISSUE TITLE
TLS: glftpd doesn't provide chain certificates

### ISSUE THREAD

**Issue by BaneHardy** [glftpd/glftpd#71]
It seems only the first certificate from the `CERT_FILE` is provided to the client during TLS handshake even when the file contains more than one certificate.
This makes it impossible for a client to verify the certificate chain properly.
Using valid TLS certificates from issuers like letsencrypt then becomes pointless.
Please have glftpd send all certificates from that file or introduce a new config option for the chain, e.g. `CHAIN_FILE`.

**Comment by glftpd** [comment]
Good idea. done :)
