### ISSUE TITLE
need glftpd option  for  more  server add in on glftpd please

### ISSUE THREAD

**Issue by s4n3y** [glftpd/glftpd#74]
need glftpd option  for  more  server add in on glftpd please

can you add this option to next glftpd version  please  ?

dont need drftpd ! i  loved glftpd can you help many off user ?

respect glftpd best and only the number one ftp ;-)

**Comment by hrxcodes** [comment]
It does not work that way. There's a lot of things you're jumping over as if it was a switch to toggle, it's a lot more complicated than that.

`/close`

**Comment by glftpd** [comment]
There are no plans to support server linking in glftpd.
