### ISSUE TITLE
sitewho problem with terminal, as raw command with glftpd works flawless

### ISSUE THREAD

**Issue by onlinewurm** [glftpd/glftpd#75]
i have the problem when i access sitewho via terminal shell it doesn't show me all the infos. i have edited the sitewho.conf and set 2 more grps as hidden and a path for the STAFF folder after that it shows me no more infos about the files that are being transferred and the total bandwidth is not correct anymore, it shows something around 1mb. I take the original sitewho.conf it shows everything without problems, i noticed it when i installed the slvprebw script. but if i call sitewho via raw command via glftpd, it shows everything properly, only via ssh terminal not! although ipc fits.

> | user1          /GRP1        | Idle: 00:00:07  |   0%:                 |
| No Tagline Set              | since 12:30:37  | file:                 |
+-----------------------------------------------------------------------+
| user2          /GRP2        | Idle: 00:00:00  |   0%:                 |
| No Tagline Set              | since 00:11:11  | file:                 |
+-----------------------------------------------------------------------+
| Up:  0 /       0KB/s | Dn:  0 /       0KB/s | Total:  0 /       0KB/s |
| Currently 18 of 20 users are online...                                |
`-----------------------------------------------------------------------'

short note: the problem is only with the current stable of debian (bookworm), the previous version runs without problems as terminal/raw mode!

**Comment by glftpd** [comment]
sorry but what is sitewho ? doesnt seem to belong to glftpd ?
