### ISSUE TITLE
Allow masks in "noretrieve"

### ISSUE THREAD

**Issue by hrxcodes** [glftpd/glftpd#76]
> noretrieve <filename> [filename ...]
>	Specifies files that cannot be downloaded.
>	Password files and other sensitive files should be listed here.
>
>	Multiple lines allowed, each max 50 filenames.

Currently the only other way I see is using either:
* `pre_fxp_check <filepath> [pathmask]`
* `cscript retr pre`

Example usage: `noretrieve passwd passwd- *.bak *.tmp *.swp *.bad`

**Comment by glftpd** [comment]
done
