### ISSUE TITLE
using a banner with the tls_ftps option results in an invalid handshake

### ISSUE THREAD

**Issue by d4shie** [glftpd/glftpd#78]
When the `banner` option is used alongside `tls_ftps` (implicit ssl), glftpd sends the banner prior to a handshake being initiated.
Clients using implicit ssl do not expect non-handshake data to be sent, resulting in the client failing to connect.

This can be reproduced by setting the `banner` option to a non-empty file, setting the `tls_ftps` option to `1`, and trying to connect with any FTP client that supports implicit ssl. The client will fail to connect, likely citing "invalid ssl version". The `openssl s_client -connect ip:port -trace -debug` command can be used to debug this (seeing that the banner data is sent prior to a handshake being finalized).

**Comment by glftpd** [comment]
fixed
