### ISSUE TITLE
Multi-line responses in site commands are not RFC 959 compliant

### ISSUE THREAD

**Issue by d4shie** [glftpd/glftpd#79]
glFTPd's multi-line responses to `SITE` commands (both built-in, such as `SITE HELP`, as well as custom ones (see example below) are not compliant with [RFC 959](https://www.rfc-editor.org/rfc/rfc959) (page 36) which states:
> Thus the format for multi-line replies is that the first line will begin with the exact required reply code, followed immediately by a Hyphen, "-" (also known as Minus), followed by text.  The last line will begin with the same code, followed immediately by Space <SP>, optionally some text, and the Telnet end-of-line code.

In the RFC, there is no reply code prefix for lines other than the first and last, however, glFTPd multi-line responses consist of the response code and a hyphen being included in all messages except the last one, such as:
> 200- First line
> 200- Second line
> 200- 234 A line beginning with numbers
> 200 Command Successful.

As mentioned before, this can be seen in `SITE HELP`, as well as custom-implemented commands; An example command script that can be used for testing is `echo -e "First line\nSecond line\n234 A line beginning with numbers"`; In all cases, the final message seems to always be sent in compliance with the spec (`200 Command Successful.`) without a hyphen.

**Comment by glftpd** [comment]
do you have an example of some other ftpd that works your way ?

**Comment by d4shie** [comment]
Sorry that I'm horribly late to respond to this - life gets busy for us all :) - No, not really, as I don't have much exposure in using, let alone administering other ftpds, but it had broken a few badly-coded libraries in C# land -- This is no-longer an issue for me, as it's been worked around, but might want to fix it next update regardless, up to you on closing this :)
