### ISSUE TITLE
ssl negotiation problems

### ISSUE THREAD

**Issue by h-0-s-h** [glftpd/glftpd#8]
200 glFTPd 2.07.1 (Dec 27 2016) 64BiT Linux+TLS(OpenSSL 1.1.0c  10 Nov 2016)+SSP
AND
200 glFTPd 2.08 BETA2 (Feb  1 2017) 64BiT Linux+TLS(OpenSSL 1.1.0d  26 Jan 2017)+SSP

[LOCALHOST][27/08/2017 12:44:33]: STOR 06-the_edenites-time__time_again_(vortex_mix)-6dd2a2c1.mp3
[LOCALHOST][27/08/2017 12:44:33]: 150 Opening BINARY mode data connection for 06-the_edenites-time__time_again_(vortex_mix)-6dd2a2c1.mp3 using SSL/TLS.
**[LOCALHOST][27/08/2017 12:44:33]: 426 Data Connection: Success.
[LOCALHOST][27/08/2017 12:44:33]: PASV**
[LOCALHOST][27/08/2017 12:44:33]: 227 Entering Passive Mode (4,2,2,2,4,74)

**Comment by glftpd** [comment]
is there something in the log files ?

**Comment by Skeddie** [comment]
I believe this is fixed since 2.08 BETA3. Please test again. If the problem persists, this issue can be reopened.
