### ISSUE TITLE
Feature Request: CLNT feature & command support

### ISSUE THREAD

**Issue by d4shie** [glftpd/glftpd#81]
Note to readers: This was initially discussed on IRC with regard to implementing third-party patches into upstream source.

The `CLNT` server feature and command is used to inform an FTP site what client a user is connecting with. It is an optional, but neat part of FTP extensions which allows site operators to allow/denylist clients, as well as help non-tech-savvy users debug their issues with a little more ease.

Once the server advertises `CLNT` in its `FEAT` command, Clients *may* send the `CLNT` command to inform the server of their User-Agent. The server may then change its behavior appropriately (the patches used on my site, for example send a different listing with different symlinks based on the user's client, retaining default behavior when the `CLNT` command was not sent for a connection). It's also used to denylist FileZilla from connecting whatsoever.

It is worth noting that certain clients like cbftp do not send `CLNT` regardless of feature support, and the user-agent used may be any string, including any version numbers associated with the client in use - As such, this may not be a 100% fool-proof way of detecting which client the user is using, and may be patched away from clients such as FileZilla (in my example), but for the use-cases where this would be assistive instead of allow/denylisting, that does not matter.

**Comment by glftpd** [comment]
Added "add_feat_capability" config option that allows you to add whatever to FEAT response. Then hooking the CLNT command should allow you to return the client agent right?
