### ISSUE TITLE
Feature Request: Support for resolving Forward-DNS IPs in users

### ISSUE THREAD

**Issue by d4shie** [glftpd/glftpd#82]
Note to readers: This was initially discussed on IRC with regard to implementing third-party patches into upstream source.

As it stands, the implementation of DNS in glftpd only resolves reverse DNS records. This results in cases where a user with a highly dynamic IP address but no reverse IP hostname (this seems to be common for Eastern European countries) has to have their IP address added to the site constantly.

While there are solutions to this, they usually involve some kind of caveats;
  - `SITE ADDIP <username> *@*` is completely insecure, and opens the site up to any scanner and attacker.
  - A cronjob which looks up a list of DNS records and adds the IPs they resolve to to a given user may be run out-of-sync with an IP change, resulting in a delay between the user's IP changing (alongside their Dynamic DNS record), and the user being given access to the site again.
  - Manually having the user add their new IP can be tedious and annoying, especially if the user is not tech-savvy themselves.

Ignoring the obvious security hole of letting a user change their own IP (let's all assume that this is intended behavior for a site running with this mode on), the solution I'd like to see implemented would take the DNS records added to each user's account, resolve them all with the system resolver (or a defined upstream resolver) - caching for a given time if provided -, and if the incoming IP address is allowlisted, proceed with login, otherwise deny access without a reverse DNS lookup.

This would also allow site operators to not have to allowlist a whole residential hostname of IPs (e.g.: `host-*.retail.xxxxxxxxxxxxxxxx.tld`) if a user has a "jumpy" IP address

**Comment by glftpd** [comment]
added. see if you can test the dev version in #glftpd on efnet
