### ISSUE TITLE
site wipe / wipe -r does not update dirlog

### ISSUE THREAD

**Issue by Termin8or666** [glftpd/glftpd#84]
docs says it should but never worked as long as I can remember, maybe it broke with earlier dirlog fixes.

**Comment by glftpd** [comment]
seems to work fine for me ?
tried :
mkdir W
site new shows W
site wipe W
site new doesnt show W

**Comment by Termin8or666** [comment]
but site search will show it as an entry but deleted ?

**Comment by glftpd** [comment]
Yeah seems site search doesnt skip deleted entries. But it should behave the same way if you delete it the normal way and not using site wipe right ?

site search also shows nuked directories so maybe its fine... Maybe it just should say "DELETED" ?

**Comment by glftpd** [comment]
ill just change it to skip deleted entries in site search
