### ISSUE TITLE
New Feature Request: gl_spy refresh choosing at start

### ISSUE THREAD

**Issue by nagye** [glftpd/glftpd#87]
Hello,
Adding an option to gl_spy so at start refresh rate could be choosen would be great.
Currently refresh rate is always at default 24/32. Then need to manualy increase to 32, which is max.
Would be great to have an option to start it at 32 (something like -refresh 32 for example) or have it start at default maximum refresh of 32.
Thank you!

**Comment by glftpd** [comment]
added -t <1-32> parameter. Thanks for the idea.
