### ISSUE TITLE
Xmas Question QoS ifgroup loop :)

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#88]
Hi, as christmas is approaching again, i wanted to ask if you could fulfill a wish for me.
i would like to have a function similar to the ifip loop, only limited to group/user.
the point is that i would like to preorize with qos service a group via iptables/tc so that 
the bandwidth would be fully usable under the group SiteOps when it is needed, if another group
is now using the bandwidth.
	
```
ifgroup =SiteOps =StaffMember
      pasv_ports 1000-2000
	  elsegroup
	  pasv_ports 3000-4000
endifgroup
```

the iptable/tc works perfectly! only the glftpd loop is missing, then it would also work here, I have tested other services with it!

as an example for emby

```
tc qdisc add dev enp7s0 root handle 1: htb default 20 r2q 100
tc class add dev enp7s0 parent 1: classid 1:1 htb rate 1gbit
tc class add dev enp7s0 parent 1:1 classid 1:10 htb rate 100mbit ceil 1gbit quantum 1500
tc class add dev enp7s0 parent 1:1 classid 1:20 htb rate 900mbit ceil 1gbit quantum 1500
iptables -t mangle -A OUTPUT -p tcp --sport 8096 -j MARK --set-mark 10
iptables -t mangle -A OUTPUT -p tcp --sport 8920 -j MARK --set-mark 10
tc filter add dev enp7s0 protocol ip parent 1:0 prio 1 handle 10 fw flowid 1:10
```

**Comment by glftpd** [comment]
Its a bit problematic since when the config file is being loaded the user isnt logged in yet...

**Comment by PatriotM** [comment]
Killall -r glftpd:* will forced to reconnect all :-)

**Comment by glftpd** [comment]
thats not the problem but the ifs are calculated when reading the config and the user isnt logged in yet :)

**Comment by glftpd** [comment]
done :)
