### ISSUE TITLE
merge insert from single add glupdate.c

### ISSUE THREAD

**Issue by PatriotM** [glftpd/glftpd#89]
first of all, a big thank you for the latest update!

the glupdate.c was modified a long time ago (from someone in the glftpd channel, i can't remember his name) so that you can also add a single dir add, it would be great if you could possibly merge it into the official glftpd release.

with the switch -s, it works great, the only thing that might be missing is whether it checks if the directory has already been imported so that it doesn't try again, but even if not it works 1a, there are no duplicate entries :)

[glupdate_patched_Hujer.zip](https://github.com/user-attachments/files/18244389/glupdate_patched_Hujer.zip)

> {
> 	printf ("glftpd DIRLOG update utility v3.1\n\n");
>         printf ("glupdate [-r /pathto/glftpd.conf] [-i ...] [-h] [-s] <full directory path>\n Options:\n"
>                " -r /path/file : alternative path to config file\n"
>                " -i ...        : unlimited number of dirs to skip\n"
>                "                 \".\", \"..\" and \"groups\" are skipped by default\n"
>                **" -s            : single update only, i.e. do not update the entire dirname of the dir\n"**
>                " -h            : this screen\n");
> 	exit (0);
> }

**Comment by glftpd** [comment]
thanks added
