### ISSUE TITLE
ERROR : glftpd crashed while initializing

### ISSUE THREAD

**Issue by r00z3r** [glftpd/glftpd#9]
Hello,

Got a weird behavior (below) : 
Sun Jan 28 12:04:00 2018 [23543   ] ERROR : glftpd crashed while initializing
Sun Jan 28 12:04:00 2018 [23543   ] ERROR : signal was received while we were blocking signals or while we were uid 0 -> skipping logout procedures and stopping glftpd

Strace on PID give that (at the end) : 
[pid 23543] fstat(5, {st_mode=S_IFREG|0644, st_size=523, ...}) = 0
[pid 23543] read(5, "USER Added by glftpd\nGENERAL 0,0"..., 4096) = 523
[pid 23543] close(5)                    = 0
[pid 23543] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2945, ...}) = 0
[pid 23543] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2945, ...}) = 0
[pid 23543] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fff806ee15f} ---
[pid 23543] geteuid()                   = 0
[pid 23543] rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [SEGV], 8) = 0
[pid 23543] geteuid()                   = 0
[pid 23543] getpid()                    = 23543
[pid 23543] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2945, ...}) = 0
[pid 23543] geteuid()                   = 0
[pid 23543] setresuid(-1, 0, -1)        = 0
[pid 23543] open("/ftp-data/logs/error.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 5
[pid 23543] fcntl(5, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
[pid 23543] write(5, "Sun Jan 28 12:04:00 2018 [23543 "..., 78) = 78
[pid 23543] fcntl(5, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
[pid 23543] close(5)                    = 0
[pid 23543] setresuid(-1, 0, -1)        = 0
[pid 23543] geteuid()                   = 0
[pid 23543] geteuid()                   = 0
[pid 23543] getpid()                    = 23543
[pid 23543] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2945, ...}) = 0
[pid 23543] geteuid()                   = 0
[pid 23543] setresuid(-1, 0, -1)        = 0
[pid 23543] open("/ftp-data/logs/error.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 5
[pid 23543] fcntl(5, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
[pid 23543] write(5, "Sun Jan 28 12:04:00 2018 [23543 "..., 168) = 168
[pid 23543] fcntl(5, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
[pid 23543] close(5)                    = 0
[pid 23543] setresuid(-1, 0, -1)        = 0
[pid 23543] geteuid()                   = 0
[pid 23543] exit_group(33)              = ?
[pid 23543] +++ exited with 33 +++
<... epoll_wait resumed> 0x562b8fe25ab0, 32, -1) = -1 EINTR (Interrupted system call)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23543, si_uid=0, si_status=33, si_utime=0, si_stime=0} ---
sendto(4, "\21", 1, 0, NULL, 0)         = 1
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
epoll_wait(3, [{EPOLLIN, {u32=5, u64=5}}], 32, -1) = 1
recvfrom(5, "\21", 1024, 0, NULL, NULL) = 1
recvfrom(5, 0x7f45aad314c0, 1024, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 33}], WNOHANG, NULL) = 23543
wait4(-1, 0x7fff80ada2f4, WNOHANG, NULL) = -1 ECHILD (No child processes)
epoll_wait(3,

This seems to be just for some clients/ip/computers, other can login without process crash
I tried to use another login that crash elsewere on my side and it works with the same clients versions, same OS, same patch level.
Can you please enlight me about this issue ?

Thanks,
Regards

**Comment by glftpd** [comment]
if its possible to replicate then please poke Hujer on irc on efnet

**Comment by r00z3r** [comment]
As discussed with Hujer, the issue was related to a userfile with an empty ipaddr.
Like : IP *@
Thanks a lot Hujer for the help.
I think deamon must catch this exception to log something helpful, because issue was weird (some users could connect anyway and some others don't).
Thanks again!

**Comment by glftpd** [comment]
added some checks to throw an error instead of crashing
